# Generated by Django 3.2.7 on 2021-09-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
    ]
