# Generated by Django 3.2.7 on 2021-10-01 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0014_auto_20211001_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, default=[], related_name='courses_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
